[tool.kedro]
package_name = "big_data_project"
project_name = "Big_Data_Project"
kedro_init_version = "0.18.11"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov src/big_data_project -ra"""

[tool.coverage.report]
fail_under = 0
show_missing = true
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]
